### ISSUE TITLE
please update pm5 and protocol

### ISSUE THREAD

**Issue by Wyze3306** [ethaniccc/Esoteric#36]
please update pm5 and protocol

**Comment by mmm545** [comment]
#35

**Comment by cqdetdev** [comment]
goof ah cuh

**Comment by cqdetdev** [comment]
it Is because the x-intercept pocketMine update broke the Dragonfly unix Socket which as a result created Race condition amongst the 20 Kill Aura checks

**Comment by cqdetdev** [comment]
edp is gay

**Comment by cqdetdev** [comment]
ethaniccc pp pics leaked at https://pnrtscr.com/kqrkc

**Comment by cqdetdev** [comment]
ذَٰلِكَ ٱلْكِتَـٰبُ لَا رَيْبَ ۛ فِيهِ ۛ هُدًۭى لِّلْمُتَّقِينَ ٢

**Comment by cqdetdev** [comment]
the bible is a false, corrupted book made by shirk committing infidels. Polytheists who pray to both a man and God? Read the Noble Qu'ran and repent for Allah is All-Forgiving.

**Comment by cqdetdev** [comment]
There is not one line in the Bible that affirms Jesus to be God, and even if that were true, that directly contradicts the dozens of lines of scripture that states he is a prophet.

**Comment by cqdetdev** [comment]
The Holy Trinity didn't exist before the time of Jesus, it couldn't be possible. So why do these infidels pray to an idea that hasn't existed even forever, like God.

**Comment by HashimTheArab** [comment]
LOOL

**Comment by mmm545** [comment]
wtf
